<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Portfolio</name>
   <tag></tag>
   <elementGuidId>32bab046-a94e-4028-92d2-31832bbfcae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutual Fund'])[1]/following::div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.menu-secondary.rounded-md.px-3.py-1.flex.flex-row.items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f01321c1-5da8-42f7-80d1-0ec86a2bdebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-secondary rounded-md px-3 py-1 flex flex-row items-center</value>
      <webElementGuid>26f4f055-3455-4dac-a86e-f106a79a07c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>f4c13a8a-dfe4-4d5a-ab59-20ab7618c099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Portfolio</value>
      <webElementGuid>8617d434-4093-40a7-b1b6-8ac18a38aec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;__className_d65c78 max-h-screen&quot;]/div[@class=&quot;xl:h-screen xl:max-h-screen flex flex-col justify-between dark:bg-black bg-foreground xl:text-xs sm:text-xxs mobile:text-xxs w-screen overflow-y-hidden&quot;]/header[@class=&quot;z-20 sticky top-0  w-screen order-first flex bg-white dark:bg-bahana-dark shadow-header&quot;]/div[@class=&quot;flex flex-wrap xl:flex-nowrap mobile:justify-around border-b dark:border-b-bahana-dark w-full&quot;]/nav[@class=&quot;order-3 xl:order-2 flex flex-col mobile:justify-around border-e dark:border-e-slate-600 border-s dark:border-s-slate-600 w-full&quot;]/div[@class=&quot;mobile:hidden xl:flex items-center justify-center h-full&quot;]/div[@class=&quot;flex items-center justify-center&quot;]/div[@class=&quot;flex gap-1 text-sm&quot;]/div[@class=&quot;cursor-pointer&quot;]/div[@class=&quot;menu-secondary rounded-md px-3 py-1 flex flex-row items-center&quot;]</value>
      <webElementGuid>24c49ed7-cdb4-4969-94fe-07bfe6cc83d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutual Fund'])[1]/following::div[3]</value>
      <webElementGuid>8aa36cee-9a6a-4909-9bc1-46497ae39d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonds'])[1]/following::div[5]</value>
      <webElementGuid>7f63a33d-4249-4aac-aaac-1f54011cd0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction'])[1]/preceding::div[1]</value>
      <webElementGuid>c4285dde-6ca5-43ac-9b21-576c68340ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div</value>
      <webElementGuid>f9861b4c-52ab-48e0-a552-1b880b3d0b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Portfolio' or . = 'Portfolio')]</value>
      <webElementGuid>9a4c92a5-9319-4067-8be8-bff4a7bfc6f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
