<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Government Bonds_1</name>
   <tag></tag>
   <elementGuidId>d5c3f34d-3962-4f3c-9cab-e6161ea34260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-tabs-tab-:ru:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>943f39af-72f9-44e4-aab1-4356887c4941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:text-bahana-primary px-2 pt-2 pb-1 text-sm pr-12 inline-block w-full text-bahana-gray-txt dark:text-bahana-ash dark:hover:text-bahana-primary hover:text-bahana-sky font-medium</value>
      <webElementGuid>b0cbdf80-ba0d-4987-adb9-ba07318fb6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:ru:</value>
      <webElementGuid>a0416944-8829-486e-8144-20f86bf0ff09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>dd1b43ea-30b0-4b5a-b21f-07de49b56cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d78541b-cf10-40cf-80a4-eecce5747553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eaaf9bc2-0d9e-42b9-8183-c285b52b1573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3ac8b965-edd7-4d3e-ad90-a7f57ce65a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Government Bonds</value>
      <webElementGuid>2c428cb0-e48d-41d4-b13d-9eee4233b448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:ru:&quot;)</value>
      <webElementGuid>2866b307-0ce7-4be0-b971-5d093dfa95e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-tabs-tab-:ru:']</value>
      <webElementGuid>4e9b12be-31b7-4153-8127-dbf50f3dd0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passive income tiap bulan.'])[1]/following::button[1]</value>
      <webElementGuid>077142a9-c2a3-4c36-a9a7-9d67f9d05857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kenali apa itu Bonds'])[1]/following::button[1]</value>
      <webElementGuid>ab2f51a9-21fa-4e39-be91-d788c041c507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBN Retail'])[1]/preceding::button[1]</value>
      <webElementGuid>c66a69ce-c08a-48e4-9af0-a0fb9a0e098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Bonds'])[1]/preceding::button[2]</value>
      <webElementGuid>d615f8e0-6756-4262-87e4-c71aaf6761de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Government Bonds']/parent::*</value>
      <webElementGuid>6ce3dfe3-fa38-4d18-b557-b69900809260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>18d4b1d0-1976-4e3c-9fc3-f875d61b60ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-tabs-tab-:ru:' and @type = 'button' and (text() = 'Government Bonds' or . = 'Government Bonds')]</value>
      <webElementGuid>2eff020d-b869-4ef4-abb5-fe5e1ea42119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
