<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADHI4DCN2 (TBC by IDX)Obligasi Berkelan_f7cbd6</name>
   <tag></tag>
   <elementGuidId>843e6d41-2675-4e49-8fee-0da97312d185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grow.shrink.basis-0.flex-col.justify-start.items-center.inline-flex.pt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cell-bond_name-185']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f180b9e3-4a7f-49a7-9e60-5f0cff3b8277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grow shrink basis-0 flex-col justify-start items-center inline-flex pt-4</value>
      <webElementGuid>a4cb3222-ca81-458d-ae20-37ac66a68ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADHI4DCN2 (TBC by IDX)Obligasi Berkelanjutan IV Adhi Karya Tahap II Tahun 2025 Seri D</value>
      <webElementGuid>4a9cd122-992a-42d4-9fa7-fa82c9908590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-bond_name-185&quot;)/div[@class=&quot;w-full self-stretch h-[5rem] px-2 py-2 rounded-lg justify-start items-start gap-3 inline-flex cursor-pointer&quot;]/div[@class=&quot;grow shrink basis-0 flex-col justify-start items-center inline-flex pt-4&quot;]</value>
      <webElementGuid>6d388b4d-7189-4a8c-ba2b-8282f746e80d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cell-bond_name-185']/div/div[2]</value>
      <webElementGuid>22d3ea7d-0c6c-4b7d-9921-cf6bb457ad9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode Penawaran'])[1]/following::div[21]</value>
      <webElementGuid>eb118c2f-46e4-4093-8f73-36b8169583c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jatuh Tempo'])[1]/following::div[29]</value>
      <webElementGuid>904e4777-e421-4ea3-8f0d-2c42278ca3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]</value>
      <webElementGuid>a2a6faaf-567d-4f13-a6b8-f4070524507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ADHI4DCN2 (TBC by IDX)Obligasi Berkelanjutan IV Adhi Karya Tahap II Tahun 2025 Seri D' or . = 'ADHI4DCN2 (TBC by IDX)Obligasi Berkelanjutan IV Adhi Karya Tahap II Tahun 2025 Seri D')]</value>
      <webElementGuid>422638c6-5af8-4d58-980d-476ddb59db01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
