<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal Bank Account_nama_pemilik_rek</name>
   <tag></tag>
   <elementGuidId>db3db8f7-0fcd-43f9-ae0e-4115a49c9379</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floating_fillednama_pemilik_rek</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_fillednama_pemilik_rek']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f98e78e-29aa-4b41-a863-ddc6dbf7136b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_fillednama_pemilik_rek</value>
      <webElementGuid>41dba8c0-6015-48fb-8912-0f4a227307c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-bahana-black block rounded-lg px-2.5 pb-2.5 pt-5 w-full text-sm bg-gray-25 dark:bg-black border-2 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer border-gray-300 disabled:bg-[#F2F2F2]</value>
      <webElementGuid>3d0037a2-fed1-4ec7-a3b3-eae636c420cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>65c024f5-fa76-4b39-b11d-b632e02a36f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>6843db51-72ec-4a5f-806a-e40bf347ad9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22db9833-83e6-4ed2-a7dc-acaaf5545f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_pemilik_rek</value>
      <webElementGuid>5b6b663b-2b4f-4c20-8fbc-91c8a80249ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_fillednama_pemilik_rek&quot;)</value>
      <webElementGuid>b02b92d6-892d-4325-ba9e-c2103b876c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_fillednama_pemilik_rek']</value>
      <webElementGuid>488faff1-2670-4507-a7e7-71bb7065d5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>d0e80023-f089-42b0-868f-cb652b45cbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_fillednama_pemilik_rek' and @type = 'text' and @name = 'nama_pemilik_rek']</value>
      <webElementGuid>0406ad11-4690-41f2-9b0a-5e96f19aa4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
