<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_checked-checkbox</name>
   <tag></tag>
   <elementGuidId>a68c5a5a-22f7-4995-b5b6-3da599db6361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checked-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checked-checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec79fbd6-1c3e-45a6-8287-65a051b09d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checked-checkbox</value>
      <webElementGuid>6af7c553-ee76-4512-9281-56e1bbdeccb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1.5 w-3 h-3 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600</value>
      <webElementGuid>90a57779-3100-4ac9-940d-cd2b2aec5cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cc2ed148-38de-4fc1-b8ed-d50e2b8947e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checked-checkbox&quot;)</value>
      <webElementGuid>fbd29f26-3ccf-459c-8865-edadffdf7d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checked-checkbox']</value>
      <webElementGuid>3d8aa5a5-7acf-4f5b-9ef8-e628fc89b0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>4d50ead9-598f-44ca-a03e-26a179646e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checked-checkbox' and @type = 'checkbox']</value>
      <webElementGuid>450c8556-3a03-4c45-90ce-75be7ce15630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
