<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Persetujuan Pembukaan Rekening Dana N_4c36a4</name>
   <tag></tag>
   <elementGuidId>c68630f3-16e6-490a-b1a9-dc7e5b6e0f87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_checked_approvel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#is_checked_approvel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93a47056-2579-4700-aac9-ec9f78f17665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox mx-2 accent-bahana-sky h-4 w-4 rounded-lg</value>
      <webElementGuid>1d94fe64-bf97-4de9-9e06-65f1530a3639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_checked_approvel</value>
      <webElementGuid>cc149182-204f-4888-b258-0abfb351837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>37f15148-418f-466f-867a-2194861beff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_checked_approvel&quot;)</value>
      <webElementGuid>30013e6c-5571-4d13-a82e-12492ac6d0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_checked_approvel']</value>
      <webElementGuid>1ca5dee7-b3bd-49da-b88f-d6b25daff0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>045c01ed-c4c0-4f96-9c7e-957c30c03410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'is_checked_approvel' and @type = 'checkbox']</value>
      <webElementGuid>e327f6ff-950a-4c47-a9d0-2f3559cb7371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
