<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Corporate Bonds</name>
   <tag></tag>
   <elementGuidId>c99ed820-8280-43bf-bb42-a760847aadae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-tabs-tab-:rp:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fc7e18b-ebcd-457c-8d0a-db3960b4a7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover:text-bahana-primary px-2 pt-2 pb-1 text-sm pr-12 inline-block w-full text-bahana-gray-txt dark:text-bahana-ash dark:hover:text-bahana-primary hover:text-bahana-sky font-medium</value>
      <webElementGuid>1447ec2c-15b7-4d46-82ee-4b428620b0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-tabs-tab-:rp:</value>
      <webElementGuid>63b33bcf-6552-47de-90d4-c6cf6e8c4093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b060d986-da3c-4742-bc5f-1d15a8373674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c20d3c3-6900-4fb7-be12-eedce812ac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>621e5192-d48e-4ff0-a183-b81d9b89e7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8a5a1f3d-1d6a-42c3-9fd2-66fce86681bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate Bonds</value>
      <webElementGuid>bba4b686-b2ca-4b1a-8273-73437a35a758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-tabs-tab-:rp:&quot;)</value>
      <webElementGuid>55aeea07-4fdc-4497-971b-d0e7de2ffd72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-tabs-tab-:rp:']</value>
      <webElementGuid>1164ce95-2bd8-445d-8f89-812d8aced45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBN Retail'])[1]/following::button[1]</value>
      <webElementGuid>f761b309-a525-452a-b47a-ce2f6a7d6879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Government Bonds'])[1]/following::button[2]</value>
      <webElementGuid>d280967a-e29c-4625-a57e-be843d3f2d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangsung'])[1]/preceding::button[1]</value>
      <webElementGuid>e0a312c5-b7b3-4f56-b38e-a50e24304e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berakhir'])[1]/preceding::button[2]</value>
      <webElementGuid>c5a40644-6041-4d50-8e6d-a6933dfae28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate Bonds']/parent::*</value>
      <webElementGuid>be628526-7121-4ae8-9870-a44410c5570a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>d3d7c449-513b-4e24-b572-b9e5662c9219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-tabs-tab-:rp:' and @type = 'button' and (text() = 'Corporate Bonds' or . = 'Corporate Bonds')]</value>
      <webElementGuid>593af6e4-6a38-4c73-9c75-279f74c4bd53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
