<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_floating_filledtanggal_lahir_1</name>
   <tag></tag>
   <elementGuidId>7cd3e0d9-4208-48d2-a81d-cd93d89a3510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filledtanggal_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floating_filledtanggal_lahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d02594e-8ac8-4332-8497-e9a7b87fa629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filledtanggal_lahir</value>
      <webElementGuid>c9141a7d-211c-4b2f-836b-77663b6cbd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bfcc2137-e520-4444-a0a7-944cd5546030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-gray-900 block rounded-lg px-2.5 text-sm bg-gray-25 dark:bg-black border-1 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer  pb-3.5 pt-4 border-gray-300 disabled:bg-[#F2F2F2] placeholder:text-[#6b7280] react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>0e83c033-526a-423d-9de1-00b08e9d3260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cd675d0-432c-4919-8801-4fd6942f2c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filledtanggal_lahir&quot;)</value>
      <webElementGuid>454d5b90-1239-481c-ac25-d2979859c772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filledtanggal_lahir']</value>
      <webElementGuid>90c5a29e-1940-488a-b050-e31ad8e4f2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-input-datepicker']/div/div/input</value>
      <webElementGuid>2285de11-12d5-4102-aa9d-d0049d541237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>bef83168-65f5-46fd-9b7b-376ddf4772b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filledtanggal_lahir' and @type = 'text']</value>
      <webElementGuid>593ad82a-f1a5-4f3e-bb28-4b8f6deba942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
