<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_floating_filledtanggal_lahir</name>
   <tag></tag>
   <elementGuidId>842dc9ee-b3a6-4bbc-b2a0-9095e343e0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filledtanggal_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floating_filledtanggal_lahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5e25d93-40e4-49a9-af34-f48f26661206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filledtanggal_lahir</value>
      <webElementGuid>f8ed743a-ed94-4b67-9738-1f08c21e88f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth </value>
      <webElementGuid>0241f4de-f7bb-48c1-846f-9be05b11d5a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d13e9f77-e142-429b-8475-1ecda419cc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-gray-900 block rounded-lg px-2.5 text-sm bg-gray-25 dark:bg-black border-1 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer  pb-3.5 pt-4 border-gray-300 disabled:bg-[#F2F2F2] placeholder:text-[#6b7280]</value>
      <webElementGuid>5879127b-712d-4522-8c87-0f868267c22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>756c1a9f-436d-4f96-9581-3db65ea328e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filledtanggal_lahir&quot;)</value>
      <webElementGuid>abfa6a5b-4b7a-4e2c-b524-abc930de3ac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filledtanggal_lahir']</value>
      <webElementGuid>7fc7ad55-9430-42ea-bde6-c98c6870dd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-input-datepicker']/div/div/input</value>
      <webElementGuid>680d769c-22b2-4c0c-8de8-6c8435a20cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>cb9d1fb4-dbef-4a0a-98b4-3557c26cd622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filledtanggal_lahir' and @placeholder = 'Date of Birth ' and @type = 'text']</value>
      <webElementGuid>371bfc05-cf76-42bc-bee3-8518aab1ba32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
