<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload</name>
   <tag></tag>
   <elementGuidId>eff640b1-5338-46ba-a223-84b653f529a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.px-4.py-2.w-full.bg-bahana-sky-btn.text-bahana-sky.text-xs.font-semibold.rounded-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Clearly Photo'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30f155d0-39bb-4818-b4fc-d2dcc9237389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 w-full bg-bahana-sky-btn text-bahana-sky text-xs font-semibold rounded-lg</value>
      <webElementGuid>4494530e-0e04-4c2d-aa0f-b9bd8a256bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>25bf1e95-0b48-4fcd-b323-f1b0cf8a025e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 max-h-screen&quot;]/div[@class=&quot;dark:text-zinc-800 flex justify-center items-center&quot;]/div[@class=&quot;w-screen self-start min-h-screen flex flex-col&quot;]/div[@class=&quot;flex-auto grid justify-center items-center bg-[#F6F6F6] dark:bg-bahana-dark pt-3&quot;]/div[@class=&quot;bg-white dark:bg-bahana-dark rounded-lg shadow p-8 w-full min-h-[700px] text-center text-sm min-w-[792px] max-w-[792px]&quot;]/div[@class=&quot;my-3&quot;]/div[@class=&quot;flex items-center pt-0 justify-center w-full&quot;]/label[@class=&quot;flex flex-col items-center justify-center w-full h-48 border-2 border-gray-300 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600&quot;]/div[@class=&quot;flex flex-col items-center justify-center p-2&quot;]/div[@class=&quot;flex justify-center gap-x-4 mt-4 w-full&quot;]/span[@class=&quot;px-4 py-2 w-full bg-bahana-sky-btn text-bahana-sky text-xs font-semibold rounded-lg&quot;]</value>
      <webElementGuid>f5c333bd-9118-479a-8156-54c0f2a2e304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clearly Photo'])[1]/following::span[1]</value>
      <webElementGuid>6a3be1ad-d1d2-43ac-9e39-b2d9caf0dad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correct'])[1]/following::span[1]</value>
      <webElementGuid>f5545994-b603-4350-91e1-9955e74d2293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Take Photo'])[1]/preceding::span[1]</value>
      <webElementGuid>ee156b1b-d591-41dc-9e85-3484a5fa54d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Face Verification'])[1]/preceding::span[1]</value>
      <webElementGuid>b2d777cc-6cf2-46c4-b6b4-2c7af8b8147b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>3ef2eece-69a2-48d4-9337-1a79fe5c3bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/span</value>
      <webElementGuid>222e2b49-caf9-472b-8eae-d4a7ca895119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload' or . = 'Upload')]</value>
      <webElementGuid>2a0b9271-b6f4-4ae9-93b4-e4a125db09d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
