<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_handphone</name>
   <tag></tag>
   <elementGuidId>8792909e-1dd9-4386-94f9-d6a455372adf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filledhandphone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floating_filledhandphone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ce4b7c1-00b6-462f-acbb-b32df490f3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filledhandphone</value>
      <webElementGuid>55cd18d1-58eb-48cd-888d-4b23cfdbfe5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-bahana-black block rounded-lg px-2.5 pb-2.5 pt-5 w-full text-sm bg-gray-25 dark:bg-black border-2 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer border-gray-300 disabled:bg-[#F2F2F2]</value>
      <webElementGuid>8469a003-d4c3-484f-9107-b638608bccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>12b81e05-819f-4c23-9a2d-6caac538e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>ca080784-2d1c-4f64-a802-191dd9f73055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>705eced1-c00c-4df3-8071-f6d2d7c7d973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>handphone</value>
      <webElementGuid>58858284-6425-4cf0-b078-458c9ba7b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filledhandphone&quot;)</value>
      <webElementGuid>8f3d6360-1603-4101-ab41-cfd19f521033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filledhandphone']</value>
      <webElementGuid>bf11a6f5-ae1b-4e30-a756-678e986c5802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/input</value>
      <webElementGuid>a78ccd78-b08f-433a-90dc-8612a652ad60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filledhandphone' and @type = 'text' and @name = 'handphone']</value>
      <webElementGuid>64d0cb62-8947-4789-9c2f-78113c1a0e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
