<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log In_username</name>
   <tag></tag>
   <elementGuidId>ca99ba1d-33d6-4393-a8bf-3fafdf17314e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floating_filledusername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filledusername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b35a3b5d-ab6b-4e0f-a9f4-903b8d5a7693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filledusername</value>
      <webElementGuid>067e18e3-9d45-436c-bde0-1068432cb038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-bahana-black block rounded-lg px-2.5 pb-2.5 pt-5 w-full text-sm bg-gray-25 dark:bg-black border-2 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer border-gray-300 disabled:bg-[#F2F2F2]</value>
      <webElementGuid>8407d0ff-3edd-4569-93ae-4f7aabb109be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9d92690-04ae-40d1-8446-6bc2a4b2465e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>fec92132-7045-4e03-9e82-e006b0857df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c516a1c-21fc-4e04-831e-5c213211f726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>e4f13e19-a8c1-4832-8ad9-535373fd3c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filledusername&quot;)</value>
      <webElementGuid>58202088-d80f-4a1c-8a78-c7d31a7548c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filledusername']</value>
      <webElementGuid>747ad33f-8ff4-4bd0-92df-2661c38f2db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fa437415-9b92-4be1-bc2d-68fccf9be9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filledusername' and @type = 'text' and @name = 'username']</value>
      <webElementGuid>ad87320c-bb48-43e7-a889-1d984c5a08da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
