<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your desired PIN_pincode-input-text_1_2</name>
   <tag></tag>
   <elementGuidId>bf669320-f640-4d11-94e3-82950d77ad98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d36f5f1c-7804-40c2-ad34-3d361c1c20ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pincode-input-text</value>
      <webElementGuid>7af7caa0-1c95-44f0-a7f2-aed2c1ed002c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>73612547-3a9f-4189-ac14-ac107983e771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>faf1a210-ade5-4394-abed-546561d578e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04fdafb5-c6a0-4515-9c37-a5a9fbc0f383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a47dd6df-e479-492a-905c-ecd648674b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7498f718-d91e-4fd9-9ab5-8d6a80c596cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>3d6cb976-e9d4-49e9-8da9-12ae49a5123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>02f8bd9f-70f4-496f-808c-a428ab5c7a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>93ea1567-93cd-4993-b8c0-8ca4364b9967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 max-h-screen&quot;]/div[@class=&quot;dark:text-zinc-800 flex justify-center items-center&quot;]/div[@class=&quot;w-screen self-start min-h-screen flex flex-col&quot;]/div[@class=&quot;fixed top-0 left-0 right-0 z-[55] w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full  backdrop-blur-[3px] bg-black bg-opacity-60
            flex justify-center items-center  min-h-screen text-xs transform transition-all duration-700 ease-in-out&quot;]/div[@class=&quot;relative w-full max-h-full max-w-[474px]&quot;]/div[@class=&quot;relative bg-white rounded-lg shadow dark:bg-bahana-dark&quot;]/div[@class=&quot;p-9 space-y-1 bg-bahana-primary rounded-lg dark:bg-bahana-black&quot;]/div[@class=&quot;w-full relative text-white text-center dark:text-white&quot;]/div[@class=&quot;space-y-3 flex items-center justify-center&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;pincode-input-text&quot;]</value>
      <webElementGuid>dc7585fc-0135-4515-a55c-1f50ec4a16f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='3']</value>
      <webElementGuid>ae94b642-0bbc-4bc5-a0a0-8ef649758c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>6269b178-e1fb-4e5f-87a4-f3d6d9cf0293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '3' and @type = 'tel']</value>
      <webElementGuid>d6f98c7e-7626-409b-8395-cd269e1d6226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
