<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Moderate_topping</name>
   <tag></tag>
   <elementGuidId>8f1f1fc3-e93e-481e-8aad-caef41264bc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declare_s_invest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#declare_s_invest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3d249ad-1e85-4db3-b7f4-8256e9e36bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declare_s_invest</value>
      <webElementGuid>31274d62-5265-4fce-aa39-eb2a274aed40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>self-start mt-1</value>
      <webElementGuid>cce46dc8-89df-4b52-8d50-92aba64b270d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6de0a78a-4c3b-425b-bfff-d37dc51868cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Paneer</value>
      <webElementGuid>3a2109c0-472b-48b4-aec4-2ba18fa85636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topping</value>
      <webElementGuid>feff8675-f443-4089-b733-507de1996906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declare_s_invest&quot;)</value>
      <webElementGuid>ba76f424-bc52-44a5-b59f-6f61ffd29fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declare_s_invest']</value>
      <webElementGuid>31a3c20e-6723-447b-ae6e-daf75c3f3144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2bbbe44e-65bb-41d3-a088-6fcc64116f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declare_s_invest' and @type = 'checkbox' and @name = 'topping']</value>
      <webElementGuid>4cd87093-8a27-4350-ba74-34e34dfe161a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
