<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading PDF_is_checked_approvel</name>
   <tag></tag>
   <elementGuidId>130fafd4-cd61-4bf0-89f4-8f1c64c91ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_checked_approvel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_checked_approvel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17773cf5-5054-40fd-ae11-39d5558768ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox mx-2 accent-bahana-sky h-4 w-4 rounded-lg</value>
      <webElementGuid>092c0b89-408a-414c-bac3-001fc6e935a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_checked_approvel</value>
      <webElementGuid>825b44bf-ad25-4acb-9fed-e7c8e5e0748b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e172747c-a35d-49c7-b3b1-7856df837ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_checked_approvel&quot;)</value>
      <webElementGuid>7dc6fc8d-ff22-4c06-9671-8d192b54696e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_checked_approvel']</value>
      <webElementGuid>e311bc61-8850-4580-8dbc-f51f51b1b9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bae0e01e-dc2f-4374-b4d9-12eef2c5872a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'is_checked_approvel' and @type = 'checkbox']</value>
      <webElementGuid>1660c5c2-e6a7-43ba-aeb1-57eb3e8cc809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
