<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Aggressive_topping</name>
   <tag></tag>
   <elementGuidId>cc7cf387-e798-4b7b-ad2f-051b469f4f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declare_s_invest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declare_s_invest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84063d60-f61b-471f-b8bc-3341d8ec4f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declare_s_invest</value>
      <webElementGuid>86374ead-85d7-4b98-aa47-6c4513b203f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>self-start mt-1</value>
      <webElementGuid>ca091a1c-6c92-4c17-ba97-d4f6e7ae9d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5b213add-7983-433b-91cc-163ebae992f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Paneer</value>
      <webElementGuid>2ca8021c-03f8-4f8d-a231-0e8a1d490f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>topping</value>
      <webElementGuid>3c2736ec-2267-4d9a-8f76-64dfe372714e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declare_s_invest&quot;)</value>
      <webElementGuid>58283046-90e6-49b6-9c04-c24da40e55b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declare_s_invest']</value>
      <webElementGuid>5fc067df-d9f8-4ac2-b52a-c24e146e6a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>000d0427-0a8a-446c-8681-4445980d57df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'declare_s_invest' and @type = 'checkbox' and @name = 'topping']</value>
      <webElementGuid>a25b6b7c-df92-4c1e-b4a1-9a4c76b28cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
