<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_floating_filleddob</name>
   <tag></tag>
   <elementGuidId>c91a6dca-ae7a-41ea-8b59-34b025aa3149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floating_filleddob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filleddob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6992129b-dc28-46b3-9621-86bb7721b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filleddob</value>
      <webElementGuid>dd937f7e-742b-4249-89e6-94e8995e54eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a10aa3d-90d6-430f-832b-46fdcaea2455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-gray-900 block rounded-lg px-2.5 text-sm bg-gray-25 dark:bg-black border-1 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer  pb-3.5 pt-4 border-gray-300 disabled:bg-[#F2F2F2] placeholder:text-[#6b7280] react-datepicker-ignore-onclickoutside</value>
      <webElementGuid>bb4f2c1c-38e1-4720-9019-b1fc57b15d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92ce48dc-f64e-4f17-a136-b8f4e8ee874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filleddob&quot;)</value>
      <webElementGuid>56c5359f-7016-4f6f-a788-60f0140c0ac0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filleddob']</value>
      <webElementGuid>02e01eca-beab-404f-b87f-d384a5d41d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-input-datepicker']/div/div/input</value>
      <webElementGuid>723dd59f-4938-4c6d-9fbe-e766799788a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>9a564978-30be-4ef0-8dd0-b1c29e58d3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filleddob' and @type = 'text']</value>
      <webElementGuid>ba3072e3-d710-4b7d-9d52-7a27ba39cb12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
