<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beneficiary Owner Address_form-radio _54758c</name>
   <tag></tag>
   <elementGuidId>f37b602a-6e1e-4ab8-9b23-f59b6aa26b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-radio.text-bahana-sky.h-5.w-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='match']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd52ba2d-ccfb-401f-b40c-a29dd54042e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-radio text-bahana-sky h-5 w-5</value>
      <webElementGuid>03b6d3ba-08d8-4d60-b85c-7038997d4768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e20fae6d-751d-49f2-9a98-c1480e61ef25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>match</value>
      <webElementGuid>a2a63b4f-6feb-44be-824c-4ee59298a4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 max-h-screen&quot;]/div[@class=&quot;dark:text-zinc-800 flex justify-center items-center&quot;]/div[@class=&quot;w-screen self-start min-h-screen flex flex-col&quot;]/div[@class=&quot;flex-auto grid justify-center items-center bg-[#F6F6F6] dark:bg-bahana-dark pt-3&quot;]/div[@class=&quot;bg-white dark:bg-bahana-dark rounded-lg shadow p-8 w-full min-h-[700px] text-center text-sm min-w-[792px] max-w-[792px]&quot;]/div[@class=&quot;grid mb-6&quot;]/div[1]/label[@class=&quot;inline-flex items-center border-2 bg-blue-100 px-4 rounded py-[18px] w-full border border-bahana-sky&quot;]/input[@class=&quot;form-radio text-bahana-sky h-5 w-5&quot;]</value>
      <webElementGuid>20012fb5-bb34-4c87-9d5d-e80cf7334ac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='match']</value>
      <webElementGuid>f9c9dc9c-bd3f-4c7c-a572-f1f3a910a864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>a76342e0-e7f7-4a16-a525-58821e5a2332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>33c21f26-1636-4c69-a532-4fbc143a07a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
