<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Place of Birth_floating_filleddob</name>
   <tag></tag>
   <elementGuidId>59d24541-0cfa-408c-8b1a-eee31c467087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filleddob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floating_filleddob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef273aaa-6d70-47ff-b430-ee3dc832c263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filleddob</value>
      <webElementGuid>d6f040fa-9ee3-4eeb-a30c-11898ac326c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>a67ebf63-9d0d-46d9-a55a-4db68236abb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1aa4aa10-8586-43a2-8859-671ef5d21b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-gray-900 block rounded-lg px-2.5 text-sm bg-gray-25 dark:bg-black border-1 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer  pb-3.5 pt-4 border-gray-300 disabled:bg-[#F2F2F2] placeholder:text-[#6b7280]</value>
      <webElementGuid>6ca41fc0-c949-4750-946e-56859f426505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e44fddfc-46ec-4fd9-8fcb-8da3d31b5952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filleddob&quot;)</value>
      <webElementGuid>5d68a892-8a5b-4c23-b550-df5d08cfabff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filleddob']</value>
      <webElementGuid>55748d27-31b5-4db8-a8c2-5648ec6f8a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-input-datepicker']/div/div/input</value>
      <webElementGuid>226e4cab-bcd0-43b2-ba66-d3b0e0790675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/input</value>
      <webElementGuid>fa805aa1-1935-4399-a120-47092550f0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filleddob' and @placeholder = 'Date of Birth' and @type = 'text']</value>
      <webElementGuid>90565392-1257-49df-855d-df6151730b0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
