<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Main Source of Income_company_name</name>
   <tag></tag>
   <elementGuidId>dca8d744-f459-4c6e-9f72-afaf77f3d14b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floating_filledcompany_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filledcompany_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>114bee68-2523-464c-a7f3-85f36c912e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filledcompany_name</value>
      <webElementGuid>601d5c59-9789-43a6-abb2-fd9418bcf99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-bahana-black block rounded-lg px-2.5 pb-2.5 pt-5 w-full text-sm bg-gray-25 dark:bg-black border-2 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer border-gray-300 disabled:bg-[#F2F2F2]</value>
      <webElementGuid>d7321fd0-8af4-4004-9843-924124184c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7323eb0a-fce2-4317-a36b-488aa06106f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-date-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>2441ba11-4712-42b6-b5f7-c00eeac637a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d2a908f-7f6a-4545-8df2-2895e3ed9fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_name</value>
      <webElementGuid>e739a123-99a0-4db1-a547-84934c07a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filledcompany_name&quot;)</value>
      <webElementGuid>1de15232-0fd8-4815-85b3-7bd5200c9217</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filledcompany_name']</value>
      <webElementGuid>75ad7099-f5be-4c14-9b27-0d373dc6ae7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>bf64764e-58b3-4f3c-9dc5-e8837cf732ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filledcompany_name' and @type = 'text' and @name = 'company_name']</value>
      <webElementGuid>4104307d-684e-4726-bc30-7b20bbd31d48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
