<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_button search_floating_filleddata_pek_568512</name>
   <tag></tag>
   <elementGuidId>fb137f7f-d3ad-46d9-9e95-5152caf14787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floating_filleddata_pekerjaan_uid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floating_filleddata_pekerjaan_uid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74878261-8bb0-43a1-93c1-d3c0b8e66edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold text-bahana-black block rounded-lg px-2.5 pb-2.5 pt-5 w-full text-sm bg-gray-25 dark:bg-black border-2 appearance-none dark:text-white dark:border-bahana-dark-border dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer border-gray-300</value>
      <webElementGuid>d15b753e-2d8c-4d44-9789-cef5804e754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6ceb5c4-a4e2-4d8f-8c22-a41973be2075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floating_filleddata_pekerjaan_uid</value>
      <webElementGuid>42eb5dfc-c5ce-48bc-843d-3b29be23bf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4ffad78e-e7a9-48ef-aa69-7491224d5869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d94d880-0e4e-47c2-8d37-3b0b434a6a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>83387adc-e1ac-45da-8248-58f71a0cfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>075a4178-5812-4662-b1f9-b42aeaf33d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>headlessui-combobox-label-:rp:</value>
      <webElementGuid>683dbffd-2800-4633-800f-c1ceb122a057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floating_filleddata_pekerjaan_uid&quot;)</value>
      <webElementGuid>fbd5229d-f98d-4eb1-9a13-e2c49da9806f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floating_filleddata_pekerjaan_uid']</value>
      <webElementGuid>5352f561-6998-43b0-8dbf-5ef4721d3d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f04a7a11-c9f9-4871-a30a-156d4a4c1bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'floating_filleddata_pekerjaan_uid' and @type = 'text']</value>
      <webElementGuid>5472d59b-4c35-4d26-946b-c8f29944f373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
