<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_salescode</name>
   <tag></tag>
   <elementGuidId>e1c82d91-02fc-4767-a880-71ef87c80466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > div > div > div.flex-auto.grid.justify-center.items-center.bg-\[\#F6F6F6\].dark\:bg-bahana-dark > div > div:nth-child(10) > select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='sales_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b2bca65c-fd08-4260-b531-9aa6f2340654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deposittrxcount_id</value>
      <webElementGuid>797e8768-f78c-4dd5-84c3-a9d66bc81f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> block rounded-lg px-2.5 w-full text-sm align-middle bg-gray-25 dark:bg-gray-700 border-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer pb-4 pt-3.5 disabled:bg-[#EBEBE4] text-[#6b7280]</value>
      <webElementGuid>5e632ff9-7fee-4f8a-8cc0-c575abec9f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Estimated Numbers of Charging Deposit Funds/Year0-120X>120-600X>600X</value>
      <webElementGuid>de4b3b31-ed28-44df-b69e-d959561c17af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 max-h-screen&quot;]/div[@class=&quot;dark:text-zinc-800 flex justify-center items-center&quot;]/div[@class=&quot;w-screen self-start min-h-screen flex flex-col&quot;]/div[@class=&quot;flex-auto grid justify-center items-center bg-[#F6F6F6] dark:bg-bahana-dark pt-3&quot;]/div[@class=&quot;bg-white dark:bg-bahana-dark rounded-lg shadow p-8 w-full min-h-[700px] text-center text-sm min-w-[792px] max-w-[792px]&quot;]/div[@class=&quot;relative relative mb-6 border-gray-300 border-3 rounded-lg relative&quot;]/select[@class=&quot;block rounded-lg px-2.5 w-full text-sm align-middle bg-gray-25 dark:bg-gray-700 border-2 border-gray-300 appearance-none dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 peer pb-4 pt-3.5 disabled:bg-[#EBEBE4] text-[#6b7280]&quot;]</value>
      <webElementGuid>edb6f303-43e8-4e40-8f6f-a821de524fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='deposittrxcount_id']</value>
      <webElementGuid>7c056152-daf6-4606-acbf-37cc8de85e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Transaction Value/Month'])[2]/following::select[1]</value>
      <webElementGuid>69346aa4-0772-465c-9332-5f6a609d547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment Experience'])[2]/following::select[2]</value>
      <webElementGuid>8f427e77-e00f-4f25-b03b-74de9ebe97ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Preference'])[1]/preceding::select[1]</value>
      <webElementGuid>0a24be48-565b-476e-93b0-8b4c20fec25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online'])[1]/preceding::select[1]</value>
      <webElementGuid>5eac55b1-5231-46c5-845d-9e5c3ca271da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>b61392e1-eb25-4b63-bba7-1f3a12400669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'deposittrxcount_id' and (text() = 'Estimated Numbers of Charging Deposit Funds/Year0-120X>120-600X>600X' or . = 'Estimated Numbers of Charging Deposit Funds/Year0-120X>120-600X>600X')]</value>
      <webElementGuid>02b8e816-4629-44a0-99d8-43de74c08cf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
