<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bahana DXtrade cooperates with_sk</name>
   <tag></tag>
   <elementGuidId>c1a94c01-3b36-4e7e-8e54-a1df750a4c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d787e3ab-1c25-4117-a7cd-7689f55fe4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_selected</value>
      <webElementGuid>09fcbacf-5800-4050-bd2e-90cd98e6c581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>self-start mt-1</value>
      <webElementGuid>a18e68bb-a63d-49bc-a405-63c829b74b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>124588a2-8180-4e67-b6ca-7f00b59f2a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>skCheck</value>
      <webElementGuid>d4d56b9f-2ea3-400b-99de-c4f8afc6149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sk</value>
      <webElementGuid>7f605207-4901-4e08-870b-a0e8bbaaf7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_selected&quot;)</value>
      <webElementGuid>b416b1bd-af67-44cf-9f34-77b3d64f1ede</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_selected']</value>
      <webElementGuid>65778fbd-0a2b-4632-aa4d-8d276afe2c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d1de2fd3-c117-4e37-90fb-41dadd921427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'is_selected' and @type = 'checkbox' and @name = 'sk']</value>
      <webElementGuid>5c3071a2-9b68-462f-b742-41e0c8e6197d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
