<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approval of Opening a Rekening Dana N_4231a1</name>
   <tag></tag>
   <elementGuidId>ff1fe40c-5b7c-4750-8aa9-b2c1aabec79d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_checked_approvel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#is_checked_approvel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b466e42-a7f3-47dd-81ba-1bf26984440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-checkbox mx-2 accent-bahana-sky h-4 w-4 rounded-lg</value>
      <webElementGuid>524f3394-d30a-4556-bd45-0fa8fc9976f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_checked_approvel</value>
      <webElementGuid>a0664337-33d5-4fb9-aed4-3391e1b67f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e9c8bd53-b172-4c22-8fc4-7ac816026e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_checked_approvel&quot;)</value>
      <webElementGuid>7f189ada-a235-4fe2-84e1-f15b00cf78ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_checked_approvel']</value>
      <webElementGuid>ad8fb928-1a00-42a8-bb87-d59c24d23dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f71bb013-d1a5-433e-9086-0ee390d7455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'is_checked_approvel' and @type = 'checkbox']</value>
      <webElementGuid>8deb6629-a8b8-4526-a7ea-e23eb7460f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
